name: deploygit 
on: 
  push:
    branches:
      - main
jobs:
  deploy-preprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.6'

      - name:  folder install
        run: cd front && yarn && yarn build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy FRONT with rsync
        run: rsync -avz ./front/out ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/data/sites/web/devatelierdesignbe/www/BERTONE
      
      - name: Deploy API with rsync
        run: rsync -avz ./admin/themes/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/data/sites/web/devatelierdesignbe/www/BERTONE/admin/wp-content/themes/bertone